routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SubscriberController;
use App\Models\Blog;
use App\Models\Subscriber;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [BlogController::class, 'blog'])->name('welcome.blogs');
Route::get('/show/{blog}', [BlogController::class, 'showBlog'])->name('welcome.blogs.show');
Route::get('/categories/{category}', [BlogController::class, 'category'])->name('categories.category');
Route::post('/', [SubscriberController::class, 'store'])->name('subscriber.store');

Route::middleware(['auth', 'verified'])->group(function (){
    Route::resource('blogs', BlogController::class);
    Route::get('blogs/restore/{id}', [BlogController::class, 'restore'])->name('blogs.restore');
    Route::get('/subscribers', [SubscriberController::class, 'index'])->name('subscribers.index');
    Route::delete('/subscribers/{subscriber}', [SubscriberController::class, 'destroy'])->name('subscribers.destroy');
});

Route::get('/dashboard', function () {
    $blogs = Blog::orderBy('created_at', 'DESC')->paginate(5);
    $countBlogs = Blog::all()->count();
    $trending = Blog::where('trending', '=', 1)->count();
    $subscribers = Subscriber::orderBy('created_at', 'DESC')->paginate(5);
    $countSubscribers = Subscriber::all()->count();
    return view('dashboard', compact('subscribers', 'blogs', 'trending', 'countSubscribers', 'countBlogs'));
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/categories.blade.php
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{asset('css/style.css')}}">
  @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
<div class="w-5/6 mx-auto">
    @include('layouts.header')
    <div class="flex my-12 text-center">
        <div>
            <div class="text-center my-12 font-bold text-6xl uppercase">{{$category->category}}</div>
            @foreach ($blogs as $blog)
            <a href="{{route('welcome.blogs.show', $blog->id)}}" class="w-1/3 mx-6">
                <div class="flex mb-6">
                        <img src="/images/{{$blog->image}}" alt="" width="400" height="300">
                        <div class="mx-6 text-left align-center">
                            {{-- <div class="inline-block uppercase border border-black shadow-xl shadow-black py-2 px-6 my-6">{{$blog->categories->category}}</div> --}}
                            <div class="text-xl font-bold">{{$blog->title}}</div>
                            <p class="my-6">{{Str::limit($blog->story, 700)}}</p>
                        </div>
                    </div> 
                </a>
            @endforeach
        </div>
    </div>
</div>    
    @include('layouts.footer')
    @include('layouts.scripts')
</body>
</html>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="flex justify-around column-4">
                        <div class="bg-blue-500 dark:bg-gray-800 shadow-lg rounded-md flex items-center justify-between p-3 border-b-4 border-blue-600 dark:border-gray-600 text-white font-medium group w-1/4">
                          <div class="flex justify-center items-center w-14 h-14 bg-white rounded-full transition-all duration-300 transform group-hover:rotate-12">
                            <svg width="30" height="30" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="stroke-current text-blue-800 dark:text-gray-800 transform transition-transform duration-500 ease-in-out"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                          </div>
                          <div class="text-right">
                            <p class="text-2xl">{{$countSubscribers}}</p>
                            <p>Subscribers</p>
                          </div>
                        </div>
                        <div class="bg-blue-500 dark:bg-gray-800 shadow-lg rounded-md flex items-center justify-between p-3 border-b-4 border-blue-600 dark:border-gray-600 text-white font-medium group w-1/4">
                          <div class="flex justify-center items-center w-14 h-14 bg-white rounded-full transition-all duration-300 transform group-hover:rotate-12">
                            <svg width="30" height="30" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="stroke-current text-blue-800 dark:text-gray-800 transform transition-transform duration-500 ease-in-out"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z"></path></svg>
                          </div>
                          <div class="text-right">
                            <p class="text-2xl">{{$countBlogs}}</p>
                            <p>Blogs</p>
                          </div>
                        </div>
                        <div class="bg-blue-500 dark:bg-gray-800 shadow-lg rounded-md flex items-center justify-between p-3 border-b-4 border-blue-600 dark:border-gray-600 text-white font-medium group w-1/4">
                          <div class="flex justify-center items-center w-14 h-14 bg-white rounded-full transition-all duration-300 transform group-hover:rotate-12">
                            <svg width="30" height="30" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="stroke-current text-blue-800 dark:text-gray-800 transform transition-transform duration-500 ease-in-out"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"></path></svg>
                          </div>
                          <div class="text-right">
                            <p class="text-2xl">{{$trending}}</p>
                            <p>Trending</p>
                          </div>
                        </div>
                    </div>
                    <div class="flex ">
                        <div class="relative flex flex-col me-4 min-w-0 lg:mb-0 break-words bg-gray-50 dark:bg-gray-800 w-1/2 shadow-lg rounded my-6">
                            <div class="rounded-t mb-0 px-0 border-0">
                            <div class="flex flex-wrap items-center px-4 py-2">
                                <div class="relative w-full max-w-full flex-grow flex-1">
                                <h3 class="font-semibold text-base text-gray-900 dark:text-gray-50">Subscribers</h3>
                                </div>
                                <div class="relative w-full max-w-full flex-grow flex-1 text-right">
                                <a href="{{route('subscribers.index')}}"><button class="bg-blue-500 dark:bg-gray-100 text-white active:bg-blue-600 dark:text-gray-800 dark:active:text-gray-700 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" type="button">See all</button></a>
                                </div>
                            </div>
                            <div class="block w-full overflow-x-auto w-1/2">
                                <table class="items-center w-full bg-transparent border-collapse">
                                <thead>
                                    <tr>
                                    <th class="px-4 bg-gray-100 dark:bg-gray-600 text-gray-500 dark:text-gray-100 align-middle border border-solid border-gray-200 dark:border-gray-500 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">Members</th>
                                    <th class="px-4 bg-gray-100 dark:bg-gray-600 text-gray-500 dark:text-gray-100 align-middle border border-solid border-gray-200 dark:border-gray-500 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($subscribers as $subscriber)
                                    <tr class="text-gray-700 dark:text-gray-100">
                                        <th class="border-t-0 px-4 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left">{{$subscriber->email}}</th>
                                        <td class="border-t-0 px-4 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">{{$subscriber->created_at}}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                        <div class="relative flex flex-col min-w-0 lg:mb-0 break-words bg-gray-50 dark:bg-gray-800 w-1/2 shadow-lg rounded my-6">
                            <div class="rounded-t mb-0 px-0 border-0">
                            <div class="flex flex-wrap items-center px-4 py-2">
                                <div class="relative w-full max-w-full flex-grow flex-1">
                                <h3 class="font-semibold text-base text-gray-900 dark:text-gray-50">Blogs</h3>
                                </div>
                                <div class="relative w-full max-w-full flex-grow flex-1 text-right">
                                <a href="{{route('blogs.index')}}"><button class="bg-blue-500 dark:bg-gray-100 text-white active:bg-blue-600 dark:text-gray-800 dark:active:text-gray-700 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" type="button">See all</button></a>
                                </div>
                            </div>
                            <div class="block w-full overflow-x-auto w-1/2">
                                <table class="items-center w-full bg-transparent border-collapse">
                                <thead>
                                    <tr>
                                    <th class="px-4 bg-gray-100 dark:bg-gray-600 text-gray-500 dark:text-gray-100 align-middle border border-solid border-gray-200 dark:border-gray-500 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">Title</th>
                                    <th class="px-4 bg-gray-100 dark:bg-gray-600 text-gray-500 dark:text-gray-100 align-middle border border-solid border-gray-200 dark:border-gray-500 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($blogs as $blog)
                                    <tr class="text-gray-700 dark:text-gray-100">
                                        <th class="border-t-0 px-4 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left">{{Str::limit($blog->title, 65)}}</th>
                                        <td class="border-t-0 px-4 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">{{$blog->created_at}}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/show.blade.php
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{asset('css/style.css')}}">
  @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
<div class="w-5/6 mx-auto">
    @include('layouts.header')
    <div class=" my-12">
        <a href="{{url()->previous()}}" class="mb-6 inline-block"><button class="block uppercase shadow bg-indigo-800 hover:bg-indigo-700 focus:shadow-outline focus:outline-none text-white text-xs py-3 px-10 rounded">Back</button></a>
        <div class="text-center mt-6 mx-auto">
            <h4 class="text-2xl font-semibold text-cyan-900 my-6">{{$blog->title}}</h4>
            <img src="/images/{{$blog->image}}" alt="" width="700" height="500" class="mx-auto">
            <div class="m-6">{{$blog->story}}</div>
        </div>
    </div>
</div>    
    @include('layouts.footer')
    @include('layouts.scripts')
</body>
</html>