routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SubscriberController;
use App\Models\Blog;
use App\Models\Subscriber;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [BlogController::class, 'blog'])->name('welcome.blogs');
Route::get('/show/{blog}', [BlogController::class, 'showBlog'])->name('welcome.blogs.show');
Route::get('/categories/{category}', [BlogController::class, 'category'])->name('categories.category');
Route::post('/', [SubscriberController::class, 'store'])->name('subscriber.store');

Route::middleware(['auth', 'verified'])->group(function (){
    Route::resource('blogs', BlogController::class);
    Route::get('blogs/restore/{id}', [BlogController::class, 'restore'])->name('blogs.restore');
    Route::get('/subscribers', [SubscriberController::class, 'index'])->name('subscribers.index');
    Route::delete('/subscribers/{subscriber}', [SubscriberController::class, 'destroy'])->name('subscribers.destroy');
});

Route::get('/dashboard', function () {
    $blogs = Blog::orderBy('created_at', 'DESC')->paginate(5);
    $countBlogs = Blog::all()->count();
    $trending = Blog::where('trending', '=', 1)->count();
    $subscribers = Subscriber::orderBy('created_at', 'DESC')->paginate(5);
    $countSubscribers = Subscriber::all()->count();
    return view('dashboard', compact('subscribers', 'blogs', 'trending', 'countSubscribers', 'countBlogs'));
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Blog extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'blogs';
    public $timestamps = true;

    protected $fillable = [
        "title",
        "story",
        "image",
        "category_id",
        "trending"
    ];

    public function categories(){
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\BlogRequest;
use Illuminate\Support\Facades\File;
use App\Http\Requests\EditBlogRequest;

class BlogController extends Controller
{

    public function category(Category $category){
        $categories = Category::all();
        $blogs = Blog::with('categories')->where('category_id', '=', $category->id)->paginate(8);
        return view('categories', compact('blogs', 'categories', 'category'));
    }

    public function blog(){
        $categories = Category::all();
        $blogs = Blog::with('categories')->limit(3)->get();
        $newBlogs = Blog::with('categories')->where('trending', '=', 1)->limit(6)->get();
        return view('welcome', compact(['blogs', 'categories', 'newBlogs']));
    }

    public function showBlog(Blog $blog){
        $categories = Category::all();
        return view('show', compact(['blog', 'categories']));
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $blogs = Blog::withTrashed()->with('categories')->paginate(4);
        return view('blogs.index', compact(['blogs']));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();
        return view('blogs.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(BlogRequest $request)
    {
        $blog = new Blog();

        $blog->title = $request->title;
        $blog->story = $request->story;
        $blog->category_id = $request->category;
        $intval = intval($request->trending);
        $blog->trending = $intval;

        if($request->image){
            $imageName = Str::random(10). '.' . $request->image->extension();
            $request->image->move(public_path('images'), $imageName);
            $blog->image = $imageName;
        }

        if(!$blog->save()) return redirect()->route('blogs.create')->with('error', 'Something went wrong!!');
        return redirect()->route('blogs.index')->with('success', 'Blog created!!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Blog $blog)
    {
        return view('blogs.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Blog $blog)
    {
        $categories = Category::all();
        return view('blogs.edit', compact(['blog', 'categories']));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(EditBlogRequest $request, Blog $blog)
    {
        if ($request->image) {
            $imageName = Str::random(10). '.' . $request->image->extension();
            $request->image->move(public_path('images'), $imageName);
            $oldImagePath = public_path($request->currentPhoto);

            if (File::exists($oldImagePath)) File::delete($oldImagePath);
        } else {
            $imageName = $request->currentPhoto;
        }
        $intval = intval($request->trending);

        $blog->title = $request->title;
        $blog->story = $request->story;
        $blog->image = $imageName;
        $blog->trending = $intval;
        $blog->category_id = $request->category;
        
        
        if (!$blog->save()) return redirect()->route('blogs.edit', $blog->id)->with('error', 'Something went wrong!!');


        return redirect()->route('blogs.edit', $blog->id)->with('success', 'Blog updated!!');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Blog $blog)
    {
        $image = public_path('images/'.$blog->image);

        if (!$blog->delete()) {
            return redirect()->route('blogs.index')->with('error', 'Blog could not be deleted!!');
        }
        // if (File::exists($image)) File::delete($image);

        return redirect()->route('blogs.index')->with('success', 'Blog deleted!!');

    }

    public function restore($id){
        Blog::withTrashed()->find($id)->restore();
  

        return redirect()->route('blogs.index')->with('success', 'Blog restored!!');
    } 
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/blogs/create.blade.php
<x-app-layout>
  <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          {{ __('Create Blog') }}
      </h2>
  </x-slot>
  <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="w-full rounded-xl bg-white p-4 shadow-2xl shadow-white/40">
            @if(Session::has('error'))
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 mb-5 w-full rounded" role="alert">
                {{ Session::get('error') }}
            </div>
            @endif
            @if(Session::has('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 mb-5 w-full rounded" role="alert">
                {{ Session::get('success') }}
            </div>
            @endif

          <form action="{{route('blogs.store')}}" method="POST" enctype="multipart/form-data">
             @csrf
              <div class="flex flex-col">
                <label for="text" class="mb-2 font-semibold">Title</label>
                <input type="text" name="title" id="text" class="w-full rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40" value="{{old('title')}}" />
                @error('title')
                  <span class="text-red-500">{{$message}}</span>
                @enderror
              </div>
            <div class="mb-4 flex flex-col">
              <label for="story" class="mb-2 font-semibold">Story</label>
              <textarea name="story" id="story" cols="15" rows="10" class="w-full rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40">{{old('story')}}</textarea>
              @error('story')
                  <span class="text-red-500">{{$message}}</span>
              @enderror
            </div>
            <div class="mb-4 grid grid-cols-2 gap-4">
              <div class="mb-4 flex flex-col w-full">
                <label for="age" class="mb-2 font-semibold">Image</label>
                <input type="file"name="image" id="age" class="rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40" value="{{old('image')}}"/>
                @error('image')
                  <span class="text-red-500">{{$message}}</span>
                @enderror
              </div>
              <div class="mb-4 flex flex-col w-full">
                <label for="category" class="mb-2 font-semibold">Category</label>
                <select id="category" name="category" class="rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40">
                  @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->category}}</option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="flex justify-between">
              <button type="submit" class="block uppercase mb-6 shadow bg-indigo-800 hover:bg-indigo-700 focus:shadow-outline focus:outline-none text-white text-xs py-3 px-10 rounded">Create</button>
              <div class="w-1/2">
                  <label for="trending">Trending</label>
                  <input type="checkbox" name="trending" id="trending" value="0" @if(old('trending') == 1) checked @endif onclick="check()">
              </div>
            </div> 
          </form>
        </div>
      </div>
  </div>
  <script src="{{asset('js/checkbox.js')}}"></script>
</x-app-layout>

resources/views/blogs/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Blog') }}
        </h2>
    </x-slot>
  
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div class="w-full rounded-xl bg-white p-4 shadow-2xl shadow-white/40">
            @if(Session::has('error'))
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 mb-5 w-full rounded" role="alert">
                {{ Session::get('error') }}
            </div>
            @endif

            @if(Session::has('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 mb-5 w-full rounded" role="alert">
                {{ Session::get('success') }}
            </div>
            @endif

            <form action="{{route('blogs.update', $blog->id)}}" method="POST" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                 <div class="flex flex-col">
                   <label for="text" class="mb-2 font-semibold">Title</label>
                   <input type="text" name="title" id="text" class="w-full rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40" value="{{$blog->title}}" />
                   @error('title')
                     <span class="text-red-500">{{$message}}</span>
                   @enderror
                 </div>
               <div class="mb-4 flex flex-col">
                 <label for="story" class="mb-2 font-semibold">Story</label>
                 <textarea name="story" id="story" cols="15" rows="10" class="w-full rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40">{{$blog->story}}</textarea>
                 @error('story')
                     <span class="text-red-500">{{$message}}</span>
                 @enderror
               </div>
               <div class="mb-4 grid grid-cols-2 gap-4">
                 <div class="mb-4 flex flex-col w-full">
                   <label for="age" class="mb-2 font-semibold">Image</label>
                   <div class="flex flex-col mb-2 w-full object-cover h-4/6 justify-items-start overflow-hidden">
                          <img class="w-1/2 h-full object-cover" src="/images/{{ $blog->image}}">
                          <input type="hidden" name="currentPhoto" value="{{$blog->image}}">
                  </div>
                   <input type="file"name="image" id="age" class="rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40" value="{{$blog->image}}"/>
                   @error('image')
                     <span class="text-red-500">{{$message}}</span>
                   @enderror
                 </div>
                 <div class="mb-4 flex flex-col w-full">
                   <label for="category" class="mb-2 font-semibold">Category</label>
                   <select id="category" name="category" class="rounded-lg border border-slate-200 px-2 py-1 hover:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500/40 active:ring active:ring-blue-500/40">
                     @foreach($categories as $category)
                       <option value="{{$category->id}}"@if($blog->category_id == $category->id) selected @endif>{{$category->category}}</option>
                     @endforeach
                   </select>
                 </div>
               </div>
               <div class="flex justify-between">
                <button type="submit" class="block uppercase mb-6 shadow bg-indigo-800 hover:bg-indigo-700 focus:shadow-outline focus:outline-none text-white text-xs py-3 px-10 rounded">Update</button>
                <div class="w-1/2">
                    <label for="trending">Trending</label>
                    <input type="checkbox" name="trending" id="trending" value="{{$blog->trending}}" @if($blog->trending == 1) checked @endif onclick="check()">
                </div>
              </div> 
             </form>
        </div>
    </div>
    <script src="{{asset('js/checkbox.js')}}"></script>
  </x-app-layout>

resources/views/blogs/index.blade.php
<x-app-layout>
  <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          {{ __('Blogs') }}
      </h2>
  </x-slot>
<div class="py-12">
  <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
    @if(Session::has('error'))
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 mb-5 w-full rounded" role="alert">
                {{ Session::get('error') }}
            </div>
    @endif
    @if(Session::has('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 mb-5 w-full rounded" role="alert">
                {{ Session::get('success') }}
            </div>
    @endif
    <a href="{{route('blogs.create')}}" class="inline-block"><button class="block uppercase mb-6 shadow bg-indigo-800 hover:bg-indigo-700 focus:shadow-outline focus:outline-none text-white text-xs py-3 px-10 rounded">Create new blog</button></a>
    <div class="grid gap-12 lg:grid-cols-2">
      @foreach($blogs as $blog)
      <div class="p-1 rounded-xl group sm:flex space-x-6 bg-white bg-opacity-50 shadow-xl hover:rounded-2xl">
        <img src="/images/{{$blog->image}}" alt="art cover" loading="lazy" width="500" height="500" class="h-56 sm:h-full w-full sm:w-5/12 object-cover object-top rounded-lg transition duration-500 group-hover:rounded-xl">
        <div class="sm:w-7/12 pl-0 p-5">
          <div class="space-y-2">
            <div class="space-y-4">
              <h4 class="text-2xl font-semibold text-cyan-900">{{$blog->title}}</h4>
              <p class="text-gray-600">{{Str::limit($blog->story, 100)}}</p>
            </div>
            @if ($blog->trashed())
            <div class="flex justify-between">
                <a href="{{route('blogs.restore', $blog->id)}}" class="block w-max text-red-600">Restore</a>
                <div class="text-bold uppercase">Deleted</div>
            </div>  
            @else
                <a href="{{route('blogs.show', $blog->id)}}" class="block w-max text-cyan-600">Read more</a>
            @endif
          </div>
        </div>
      </div>
      @endforeach  
    </div>
    <div class="my-4 mx-4">{{$blogs->links()}}</div>
  </div>
</div>
</x-app-layout>

resources/views/blogs/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('View Blog') }}
        </h2>
    </x-slot>
  
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div class="w-full rounded-xl bg-white p-4 shadow-2xl shadow-white/40">
            <div class="flex justify-between w-full">
                <a href="{{route('blogs.edit', $blog->id)}}"><button class="block uppercase mb-6 shadow bg-indigo-800 hover:bg-indigo-700 focus:shadow-outline focus:outline-none text-white text-xs py-3 px-10 rounded">Edit blog</button></a>
                <form action="{{route('blogs.destroy', $blog->id)}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="block uppercase mb-6 shadow bg-red-800 hover:bg-red-700 focus:shadow-outline focus:outline-none text-white text-xs py-3 px-10 rounded">Delete</button>
                </form>
            </div>
                <div class="text-center">
                    <h4 class="text-2xl font-semibold text-cyan-900 my-6">{{$blog->title}}</h4>
                    <img src="/images/{{$blog->image}}" alt="" width="700" height="500" class="mx-auto">
                    <div class="m-6">{{$blog->story}}</div>
                </div>
          </div>
        </div>
    </div>
  </x-app-layout>